version: '2'
services:
  android2:
    tty: true
    privileged: true
    stdin_open: true
    labels:
      com_mwp_conf_nginx: '[]'
      com_mwp_conf_services: '{"mDNS":false,"logger":false,"out-file":"file","eventService":false,"join_network":true,"network_host":false}'
      com_mwp_conf_storage: '{"usb":false}'
    restart: always
    image: 'android:latest'
    command: '2'
    ports:
      - '5557:5555'
    volumes:
      - './workdir/ipc:/ipc:rw'
      - './workdir/data2:/data:rw'
    mac_address: 02:42:ac:64:00:02
    networks:
      android:
        ipv4_address: 172.100.0.4
    depends_on:
      - aic-manager
